package com.mtc.entity.app;

import java.util.Date;

public class SBBbfar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.date_time
     *
     * @mbggenerated
     */
    private Date dateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.keyid
     *
     * @mbggenerated
     */
    private String keyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.t1
     *
     * @mbggenerated
     */
    private String t1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.t2
     *
     * @mbggenerated
     */
    private String t2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.t3
     *
     * @mbggenerated
     */
    private String t3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.t4
     *
     * @mbggenerated
     */
    private String t4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.t5
     *
     * @mbggenerated
     */
    private String t5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.t6
     *
     * @mbggenerated
     */
    private String t6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.h1
     *
     * @mbggenerated
     */
    private String h1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.h2
     *
     * @mbggenerated
     */
    private String h2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.p
     *
     * @mbggenerated
     */
    private String p;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.station
     *
     * @mbggenerated
     */
    private String station;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.gps
     *
     * @mbggenerated
     */
    private String gps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.help
     *
     * @mbggenerated
     */
    private String help;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.bak1
     *
     * @mbggenerated
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.bak2
     *
     * @mbggenerated
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_b_bbfar.bak3
     *
     * @mbggenerated
     */
    private String bak3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.id
     *
     * @return the value of s_b_bbfar.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.id
     *
     * @param id the value for s_b_bbfar.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.date_time
     *
     * @return the value of s_b_bbfar.date_time
     *
     * @mbggenerated
     */
    public Date getDateTime() {
        return dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.date_time
     *
     * @param dateTime the value for s_b_bbfar.date_time
     *
     * @mbggenerated
     */
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.keyid
     *
     * @return the value of s_b_bbfar.keyid
     *
     * @mbggenerated
     */
    public String getKeyid() {
        return keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.keyid
     *
     * @param keyid the value for s_b_bbfar.keyid
     *
     * @mbggenerated
     */
    public void setKeyid(String keyid) {
        this.keyid = keyid == null ? null : keyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.t1
     *
     * @return the value of s_b_bbfar.t1
     *
     * @mbggenerated
     */
    public String getT1() {
        return t1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.t1
     *
     * @param t1 the value for s_b_bbfar.t1
     *
     * @mbggenerated
     */
    public void setT1(String t1) {
        this.t1 = t1 == null ? null : t1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.t2
     *
     * @return the value of s_b_bbfar.t2
     *
     * @mbggenerated
     */
    public String getT2() {
        return t2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.t2
     *
     * @param t2 the value for s_b_bbfar.t2
     *
     * @mbggenerated
     */
    public void setT2(String t2) {
        this.t2 = t2 == null ? null : t2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.t3
     *
     * @return the value of s_b_bbfar.t3
     *
     * @mbggenerated
     */
    public String getT3() {
        return t3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.t3
     *
     * @param t3 the value for s_b_bbfar.t3
     *
     * @mbggenerated
     */
    public void setT3(String t3) {
        this.t3 = t3 == null ? null : t3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.t4
     *
     * @return the value of s_b_bbfar.t4
     *
     * @mbggenerated
     */
    public String getT4() {
        return t4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.t4
     *
     * @param t4 the value for s_b_bbfar.t4
     *
     * @mbggenerated
     */
    public void setT4(String t4) {
        this.t4 = t4 == null ? null : t4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.t5
     *
     * @return the value of s_b_bbfar.t5
     *
     * @mbggenerated
     */
    public String getT5() {
        return t5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.t5
     *
     * @param t5 the value for s_b_bbfar.t5
     *
     * @mbggenerated
     */
    public void setT5(String t5) {
        this.t5 = t5 == null ? null : t5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.t6
     *
     * @return the value of s_b_bbfar.t6
     *
     * @mbggenerated
     */
    public String getT6() {
        return t6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.t6
     *
     * @param t6 the value for s_b_bbfar.t6
     *
     * @mbggenerated
     */
    public void setT6(String t6) {
        this.t6 = t6 == null ? null : t6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.h1
     *
     * @return the value of s_b_bbfar.h1
     *
     * @mbggenerated
     */
    public String getH1() {
        return h1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.h1
     *
     * @param h1 the value for s_b_bbfar.h1
     *
     * @mbggenerated
     */
    public void setH1(String h1) {
        this.h1 = h1 == null ? null : h1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.h2
     *
     * @return the value of s_b_bbfar.h2
     *
     * @mbggenerated
     */
    public String getH2() {
        return h2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.h2
     *
     * @param h2 the value for s_b_bbfar.h2
     *
     * @mbggenerated
     */
    public void setH2(String h2) {
        this.h2 = h2 == null ? null : h2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.p
     *
     * @return the value of s_b_bbfar.p
     *
     * @mbggenerated
     */
    public String getP() {
        return p;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.p
     *
     * @param p the value for s_b_bbfar.p
     *
     * @mbggenerated
     */
    public void setP(String p) {
        this.p = p == null ? null : p.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.station
     *
     * @return the value of s_b_bbfar.station
     *
     * @mbggenerated
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.station
     *
     * @param station the value for s_b_bbfar.station
     *
     * @mbggenerated
     */
    public void setStation(String station) {
        this.station = station == null ? null : station.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.gps
     *
     * @return the value of s_b_bbfar.gps
     *
     * @mbggenerated
     */
    public String getGps() {
        return gps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.gps
     *
     * @param gps the value for s_b_bbfar.gps
     *
     * @mbggenerated
     */
    public void setGps(String gps) {
        this.gps = gps == null ? null : gps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.help
     *
     * @return the value of s_b_bbfar.help
     *
     * @mbggenerated
     */
    public String getHelp() {
        return help;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.help
     *
     * @param help the value for s_b_bbfar.help
     *
     * @mbggenerated
     */
    public void setHelp(String help) {
        this.help = help == null ? null : help.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.bak1
     *
     * @return the value of s_b_bbfar.bak1
     *
     * @mbggenerated
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.bak1
     *
     * @param bak1 the value for s_b_bbfar.bak1
     *
     * @mbggenerated
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1 == null ? null : bak1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.bak2
     *
     * @return the value of s_b_bbfar.bak2
     *
     * @mbggenerated
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.bak2
     *
     * @param bak2 the value for s_b_bbfar.bak2
     *
     * @mbggenerated
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2 == null ? null : bak2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_b_bbfar.bak3
     *
     * @return the value of s_b_bbfar.bak3
     *
     * @mbggenerated
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_b_bbfar.bak3
     *
     * @param bak3 the value for s_b_bbfar.bak3
     *
     * @mbggenerated
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3 == null ? null : bak3.trim();
    }
}